<?php

namespace AppBundle\Repository;

/**
 * AttributionProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributionProjetRepository extends \Doctrine\ORM\EntityRepository
{
}
