<?php

namespace AppBundle\Repository;

/**
 * DemandeLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
