<?php

namespace AppBundle\Repository;

/**
 * InfosTravailleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfosTravailleurRepository extends \Doctrine\ORM\EntityRepository
{
}
