<?php

namespace AppBundle\Repository;

/**
 * ProgrammeLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammeLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
