<?php

namespace AppBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{

	public function findByKeyword($keyword)
    {

        $qb = this.createQueryBuilder('p')


        return $this->getEntityManager()->createQuery('
            SELECT p
            FROM AppBundle:Projet p
            WHERE p.libelle LIKE :keyword
                  OR p.description LIKE :keyword
        ')->setParameters([
            'keyword' => '%' . $keyword . '%',
        ])->getResult();
    }
}


 