<?php

namespace AppBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{

	public function findByKeyword($keyword, $utilisateur = null)
    {

        

        /*return $this->getEntityManager()->createQuery('
            SELECT p
            FROM AppBundle:Projet p
            WHERE p.libelle LIKE :keyword
                  OR p.description LIKE :keyword
        ')->setParameters([
            'keyword' => '%' . $keyword . '%',
        ])->getResult();*/


       $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.utilisateur', 'u')
            ->where('p.libelle LIKE :keyword')
            ->orWhere('p.description LIKE :keyword')
            ->orWhere('u.adresse LIKE :keyword')
            ->setParameter('keyword', '%' . $keyword . '%');

        if (!is_null($utilisateur))
            $qb->andWhere('u.adresse = :utilisateur')
                ->setParameter('utilisateur', $utilisateur);       

        return $qb->getQuery()->getResult();
    }
}


 