<?php

namespace AppBundle\Repository;

/**
 * SolliciterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolliciterRepository extends \Doctrine\ORM\EntityRepository
{
}
