<?php

namespace AppBundle\Repository;

/**
 * TravailleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravailleurRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByKeyword($keyword)
    {
        return $this->getEntityManager()->createQuery('
            SELECT t
            FROM AppBundle:Travailleur t
            LEFT JOIN t.ville v
            LEFT JOIN v.pays p
            LEFT JOIN t.infosTravailleur it
            LEFT JOIN it.specialites sp
            WHERE t.username LIKE :keyword
              OR v.nom LIKE :keyword
              OR p.nom LIKE :keyword
              OR sp.nom LIKE :keyword
              OR sp.description LIKE :keyword
        ')->setParameters([
            'keyword' => '%' . $keyword . '%',
        ])->getResult();
    }
}
