<?php

namespace AppBundle\Repository;

/**
 * TravailleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravailleurRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByKeyword($keyword, $pays = null, $ville = null, $specialite = null)
    {
        $qb = $this->createQueryBuilder('t')
            ->leftJoin('t.ville', 'v')
            ->leftJoin('v.pays', 'p')
            ->leftJoin('t.infosTravailleur', 'it')
            ->leftJoin('it.specialites', 'sp')
            ->where('t.username LIKE :keyword')
            ->orWhere('v.nom LIKE :keyword')
            ->orWhere('p.nom LIKE :keyword')
            ->orWhere('sp.nom LIKE :keyword')
            ->orWhere('sp.description LIKE :keyword')
            ->setParameter('keyword', '%' . $keyword . '%');

        if (!is_null($ville))
            $qb->andWhere('v.id = :ville')
                ->setParameter('ville', $ville);

        if (!is_null($pays))
            $qb->andWhere('p.id = :pays')
                ->setParameter('pays', $pays);

        if (!is_null($specialite))
            $qb->andWhere('sp.id = :spec')
                ->setParameter('spec', $specialite);

        return $qb->getQuery()->getResult();
    }
}
