<?php

namespace AppBundle\Repository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends \Doctrine\ORM\EntityRepository
{


    public function listVilleByPays($pays)
    {
        $qb = $this->createQueryBuilder('v')
            ->join('v.pays', 'p')
            ->where('p.id = :id')
            ->setParameter('id', $pays)
            ->getQuery();

        return $qb->getArrayResult();
    }
}
