app2:
    resource: "@AppBundle/Controller/Frontend"
    prefix:   /
    type: annotation

#app:
    #resource: "@AppBundle/Controller/Backend"
    #prefix:   /admin
    #type: annotation

api:
    resource: "@AppBundle/Controller/API"
    prefix:   /api
    type: rest

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin