# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    
    #   couche Service       
    app.admin.metier:
        class: AppBundle\Metier\AdminMetier
        arguments: ["@doctrine.orm.entity_manager"]
    app.attributionProjet.metier:
        class: AppBundle\Metier\AttributionProjetMetier
        arguments: ["@doctrine.orm.entity_manager"]
    app.demandeLocation.metier:
        class: AppBundle\Metier\DemandeLocationMetier
        arguments: ["@doctrine.orm.entity_manager"]
    app.demandeParticipation.metier:
        class: AppBundle\Metier\DemandeParticipationMetier
        arguments: ["@doctrine.orm.entity_manager"]
    app.demandeService.metier:
        class: AppBundle\Metier\DemandeParticipationMetier
        arguments: ["@doctrine.orm.entity_manager"]
    app.entreprise.metier:
        class: AppBundle\Metier\EntrepriseMetier
        arguments: ["@doctrine.orm.entity_manager"]
    app.location.metier:
        class: AppBundle\Metier\LocationMetier
        arguments: ["@doctrine.orm.entity_manager"]
    app.note.metier:
        class: AppBundle\Metier\NoteMetier
        arguments: ["@doctrine.orm.entity_manager"]
    app.programme.metier:
        class: AppBundle\Metier\ProgrammeMetier
        arguments: ["@doctrine.orm.entity_manager"]
    app.programmeLocation.metier:
        class: AppBundle\Metier\ProgrammeLocationMetier
        arguments: ["@doctrine.orm.entity_manager"]
    app.projet.metier:
        class: AppBundle\Metier\ProjetMetier
        arguments: ["@doctrine.orm.entity_manager"]
    app.solliciter.metier:
        class: AppBundle\Metier\SolliciterMetier
        arguments: ["@doctrine.orm.entity_manager"]
    app.travailleur.metier:
        class: AppBundle\Metier\TravailleurMetier
        arguments: ["@doctrine.orm.entity_manager"]
    app.utilisateur.metier:
        class: AppBundle\Metier\UtilisateurMetier
        arguments: ["@doctrine.orm.entity_manager"]