services:
    admin.specialite:
        class: AppBundle\Admin\GestionBase\Specialite
        arguments: [~, AppBundle\Entity\Specialite, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Paramètres de Base", label: Specialite, show_mosaic_button: true }
        public: true
    admin.file:
        class: AppBundle\Admin\GestionBase\FileAdmin
        arguments: [~, AppBundle\Entity\File, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Paramètres de Base", label: Fichier, show_mosaic_button: true }
        public: true
    admin.pays:
        class: AppBundle\Admin\GestionBase\PaysAdmin
        arguments: [~, AppBundle\Entity\Pays, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Paramètres de Base", label: Pays, show_mosaic_button: true }
        public: true
    admin.ville:
        class: AppBundle\Admin\GestionBase\VilleAdmin
        arguments: [~, AppBundle\Entity\Ville, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Paramètres de Base", label: Ville, show_mosaic_button: true }
        public: true
    admin.file:
        class: AppBundle\Admin\FileAdmin
        arguments: [~, AppBundle\Entity\File, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Paramètres de Base", label: Fichier, show_mosaic_button: true }
        public: true