services:
    admin.demandeService:
        class: AppBundle\Admin\GestionService\DemandeServiceAdmin
        arguments: [~, AppBundle\Entity\DemandeService, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des Services", label: Demandes de Service, show_mosaic_button: true }
        public: true
    admin.solliciter:
        class: AppBundle\Admin\GestionService\SolliciterAdmin
        arguments: [~, AppBundle\Entity\Solliciter, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des Services", label: Solliciter un travailleur, show_mosaic_button: true }
        public: true