#fos_user
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\Utilisateur
    service:
        mailer: fos_user.mailer.twig_swift
        user_manager: pugx_user_manager
    registration:
        form:
            type: AppBundle\Form\Type\RegistrationType
        confirmation:
            enabled: true
            template:   FOSUserBundle:Registration:email.txt.twig
            from_email:
                address: symcassus@gmail.com
                sender_name: SymfonyAppTest_NoReply
    resetting:
        email:
            template:   FOSUserBundle:Resetting:email.txt.twig
            from_email:
                address: symcassus@gmail.com
                sender_name: SymfonyAppTest_NoReply
    from_email:
        address: symcassus@gmail.com
        sender_name: SymfonyAppTest_NoReply

#pugx_multi_user
pugx_multi_user:
  users:
    admin:
        entity: 
          class: AppBundle\Entity\Admin
#          factory: 
        registration:
          form: 
            type: AppBundle\Form\Type\RegistrationAdminFormType
            name: fos_user_registration_form
            validation_groups:  [Registration, Default]
          template: AppBundle:Registration:admin.form.html.twig
        profile:
          form:
            type: AppBundle\Form\Type\ProfileAdminFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default] 
    travailleur:
        entity: 
          class: AppBundle\Entity\Travailleur
        registration:
          form: 
            type: AppBundle\Form\Type\RegistrationTravailleurFormType
          template: AppBundle:Registration:travailleur.form.html.twig
        profile:
          form: 
            type: AppBundle\Form\Type\ProfileTravailleurFormType
    entreprise:
        entity: 
          class: AppBundle\Entity\Entreprise
        registration:
          form: 
            type: AppBundle\Form\Type\RegistrationEntrepriseFormType
          template: AppBundle:Registration:entreprise.form.html.twig
        profile:
          form: 
            type: AppBundle\Form\Type\ProfileEntrepriseFormType