
services:
    admin.admin:
        class: AppBundle\Admin\GestionUtilisateur\Admin
        arguments: [~, AppBundle\Entity\Admin, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des Utilisateurs", label: Admin, show_mosaic_button: true }
        public: true
    admin.travailleur:
        class: AppBundle\Admin\GestionUtilisateur\TravailleurAdmin
        arguments: [~, AppBundle\Entity\Travailleur, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des Utilisateurs", label: Travailleur, show_mosaic_button: true }
        public: true
    admin.entreprise:
        class: AppBundle\Admin\GestionUtilisateur\EntrepriseAdmin
        arguments: [~, AppBundle\Entity\Entreprise, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des Utilisateurs", label: Entreprise, show_mosaic_button: true }
        public: true

    admin.specialite:
        class: AppBundle\Admin\Specialite
        arguments: [~, AppBundle\Entity\Specialite, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Paramètres de Base", label: Specialite, show_mosaic_button: true }
        public: true
    admin.file:
        class: AppBundle\Admin\FileAdmin
        arguments: [~, AppBundle\Entity\File, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Paramètres de Base", label: Fichier, show_mosaic_button: true }
        public: true

    admin.projet:
        class: AppBundle\Admin\GestionProjet\ProjetAdmin
        arguments: [~, AppBundle\Entity\Projet, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des Projets", label: Projet, show_mosaic_button: true }
        public: true
    admin.attibutionProjet:
        class: AppBundle\Admin\GestionProjet\AttributionProjetAdmin
        arguments: [~, AppBundle\Entity\AttributionProjet, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des Projets", label: Attribuer un projet au travailleur, show_mosaic_button: true }
        public: true
    admin.demandeParticipation:
        class: AppBundle\Admin\GestionProjet\DemandeParticipationAdmin
        arguments: [~, AppBundle\Entity\DemandeParticipation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des Projets", label: Demandes de participation, show_mosaic_button: true }
        public: true

    admin.demandeService:
        class: AppBundle\Admin\GestionService\DemandeServiceAdmin
        arguments: [~, AppBundle\Entity\DemandeService, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des Services", label: Demandes de Service, show_mosaic_button: true }
        public: true
    admin.solliciter:
        class: AppBundle\Admin\GestionService\SolliciterAdmin
        arguments: [~, AppBundle\Entity\Solliciter, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des Services", label: Solliciter un travailleur, show_mosaic_button: true }
        public: true

    admin.location:
        class: AppBundle\Admin\GestionLocation\LocationAdmin
        arguments: [~, AppBundle\Entity\Location, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des Locations", label: Location, show_mosaic_button: true }
        public: true
    admin.programmeLocation:
        class: AppBundle\Admin\GestionLocation\ProgrammeLocationAdmin
        arguments: [~, AppBundle\Entity\ProgrammeLocation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des Locations", label: Programme de Location, show_mosaic_button: true }
        public: true
    admin.demandeLocation:
        class: AppBundle\Admin\GestionLocation\DemandeLocationAdmin
        arguments: [~, AppBundle\Entity\DemandeLocation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des Locations", label: Gestion des Demandes, show_mosaic_button: true }
        public: true